version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-1
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Nginx serves on port 80 internally, mapped to 5173 for your original setup
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./server-1
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - ./.env  # Root level .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
 